### ISSUE TITLE
ClientSecret tool: Fhi.HelseId.Tools release pipeline

### ISSUE THREAD

**Issue by jennyhougen** [FHIDev/Fhi.HelseId#680]
**Description**
Publish and release pipeline for ClientSecret tool in Fhi.HelseId.Tools. The pipeline should publish files, create a zip and release a new version with tag and asset with zip.

**Acceptance criteria**
- Verify that release has zipped file
- Verify that release creates a tag on the commit
- Verify that the release has correct version number

**Implementation notes**

Sample code
```
 - name: Zip Release
        run: zip -r Fhi.HelseIdSelvbetjening.CLI.zip publish_output/

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: Fhi.HelseIdSelvbetjening.CLI.zip

```
